/**
 * Flashcards Page Component
 *
 * Spaced repetition flashcard system for effective learning:
 * - Create and manage flashcard decks
 * - Study cards with flip animations
 * - Rate card difficulty (hard/good/easy)
 * - SM-2 algorithm for optimal review scheduling
 * - Generate cards from source material
 * - Track review progress and earn XP
 */

// React hooks
import { useState, useEffect } from "react";

// UI components from shadcn
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";

// Hooks and state
import { useToast } from "@/hooks/use-toast";
import { useGameStore } from "@/lib/gameStore";

// Icons from lucide-react
import {
  Layers,
  Plus,
  Sparkles,
  ChevronLeft,
  ChevronRight,
  RotateCcw,
  ThumbsUp,
  ThumbsDown,
  Meh,
  Upload,
} from "lucide-react";

// Gemini API function
import { generateFlashcards as generateFlashcardsAI } from "@/lib/gemini";

// Type definitions
import { Flashcard, FlashcardDeck } from "@/types";
import { cn } from "@/lib/utils";

/**
 * Mock flashcard data
 * In production, these would be fetched from backend or generated by AI
 */
const mockFlashcards: Flashcard[] = [];

/**
 * Flashcards Component
 *
 * Provides spaced repetition learning with:
 * - Flip card animation
 * - Difficulty rating (hard/good/easy)
 * - Deck management
 * - Generation from source material
 * - Review scheduling
 * - XP rewards
 */
export default function Flashcards() {
  // Hooks
  const { toast } = useToast();
  const { addXP, incrementStat, updateMissionProgress } = useGameStore();

  // State for cards
  const [cards, setCards] = useState<Flashcard[]>(mockFlashcards);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  // State for UI
  const [showCreate, setShowCreate] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [sourceText, setSourceText] = useState("");
  const [reviewedCount, setReviewedCount] = useState(0);

  // Current card being reviewed
  const currentCard = cards[currentIndex];

  /**
   * Handle card flip animation
   */
  const handleFlip = () => {
    setIsFlipped(!isFlipped);
  };

  /**
   * Handle difficulty rating
   * Updates spaced repetition algorithm metrics
   *
   * @param rating - User's rating: 'hard', 'good', or 'easy'
   */
  const handleRating = (rating: "hard" | "good" | "easy") => {
    incrementStat("flashcardsReviewed");
    updateMissionProgress("flashcard");
    const { xpGained } = addXP("review_flashcard");
    setReviewedCount(reviewedCount + 1);

    // Update card with SM-2 algorithm (simplified)
    const updatedCards = [...cards];
    const card = { ...updatedCards[currentIndex] };

    if (rating === "hard") {
      card.interval = 1;
      card.easeFactor = Math.max(1.3, card.easeFactor - 0.2);
    } else if (rating === "good") {
      card.repetitions += 1;
      card.interval =
        card.repetitions === 1
          ? 1
          : card.repetitions === 2
          ? 6
          : Math.round(card.interval * card.easeFactor);
    } else {
      card.repetitions += 1;
      card.interval = Math.round(card.interval * card.easeFactor * 1.3);
      card.easeFactor += 0.1;
    }

    const nextDate = new Date();
    nextDate.setDate(nextDate.getDate() + card.interval);
    card.nextReviewDate = nextDate.toISOString();
    card.lastReviewDate = new Date().toISOString();

    updatedCards[currentIndex] = card;
    setCards(updatedCards);

    // Move to next card
    if (currentIndex < cards.length - 1) {
      setCurrentIndex(currentIndex + 1);
      setIsFlipped(false);
    } else {
      toast({
        title: "Review Complete! 🎉",
        description: `You reviewed ${cards.length} cards and earned XP!`,
      });
      setCurrentIndex(0);
      setIsFlipped(false);
    }
  };

  const generateFlashcards = async () => {
    if (!sourceText.trim()) {
      toast({
        title: "Error",
        description: "Please enter some notes to generate flashcards from.",
        variant: "destructive",
      });
      return;
    }

    setIsGenerating(true);

    try {
      // Generate flashcards using Gemini API
      const generatedCards = await generateFlashcardsAI(sourceText);

      // Convert to Flashcard type with required fields
      const newCards: Flashcard[] = generatedCards.map((card, index) => ({
        id: `gen-${Date.now()}-${index}`,
        front: card.front,
        back: card.back,
        difficulty: card.difficulty,
        deckId: "1",
        interval: 1,
        easeFactor: 2.5,
        repetitions: 0,
        nextReviewDate: new Date().toISOString(),
      }));

      setCards([...cards, ...newCards]);
      setIsGenerating(false);
      setShowCreate(false);
      setSourceText("");

      toast({
        title: "Flashcards Generated! ✨",
        description: `Added ${newCards.length} new flashcards to your deck.`,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Failed to generate flashcards";
      setIsGenerating(false);
      toast({
        title: "Generation Failed",
        description: `Could not generate flashcards: ${errorMessage}`,
        variant: "destructive",
      });
    }
  };

  const difficultyColors = {
    easy: "bg-success/20 text-success",
    medium: "bg-warning/20 text-warning",
    hard: "bg-destructive/20 text-destructive",
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-display font-bold">Flashcards</h1>
          <p className="text-muted-foreground mt-1">
            Master concepts with spaced repetition
          </p>
        </div>
        <Button
          onClick={() => setShowCreate(!showCreate)}
          variant={showCreate ? "secondary" : "default"}
        >
          {showCreate ? (
            "Back to Review"
          ) : (
            <>
              <Plus className="w-4 h-4 mr-2" />
              Create Cards
            </>
          )}
        </Button>
      </div>

      {showCreate ? (
        <Card className="max-w-2xl mx-auto">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-primary" />
              Generate Flashcards from Notes
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="border-2 border-dashed border-border rounded-xl p-8 text-center hover:border-primary/50 transition-colors cursor-pointer">
              <Upload className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
              <p className="font-medium mb-1">Upload PDF or Image</p>
              <p className="text-sm text-muted-foreground">
                Drag and drop or click to browse
              </p>
            </div>

            <div className="flex items-center gap-4">
              <div className="flex-1 h-px bg-border" />
              <span className="text-sm text-muted-foreground">
                or paste notes
              </span>
              <div className="flex-1 h-px bg-border" />
            </div>

            <Textarea
              placeholder="Paste your notes here and AI will extract key concepts..."
              value={sourceText}
              onChange={(e) => setSourceText(e.target.value)}
              className="min-h-[150px]"
            />

            <Button
              onClick={generateFlashcards}
              disabled={!sourceText.trim() || isGenerating}
              className="w-full gradient-primary text-primary-foreground"
            >
              {isGenerating ? (
                <>
                  <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin mr-2" />
                  Generating Flashcards...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Generate Flashcards
                </>
              )}
            </Button>
          </CardContent>
        </Card>
      ) : cards.length === 0 ? (
        <Card className="max-w-2xl mx-auto">
          <CardContent className="flex flex-col items-center justify-center h-64 text-center">
            <Layers className="w-16 h-16 text-muted-foreground mb-4" />
            <h2 className="text-2xl font-bold mb-2">No Flashcards Yet</h2>
            <p className="text-muted-foreground mb-6">
              Generate flashcards from your notes to get started!
            </p>
            <Button onClick={() => setShowCreate(true)} className="gap-2">
              <Plus className="w-4 h-4" />
              Create Your First Flashcards
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="max-w-2xl mx-auto space-y-6">
          {/* Progress */}
          <div className="flex items-center justify-between text-sm text-muted-foreground">
            <span>
              Card {currentIndex + 1} of {cards.length}
            </span>
            <span>{reviewedCount} reviewed this session</span>
          </div>

          {/* Flashcard */}
          <div
            className={cn(
              "flip-card w-full h-[350px] cursor-pointer",
              isFlipped && "flipped"
            )}
            onClick={handleFlip}
          >
            <div className="flip-card-inner relative w-full h-full">
              {/* Front */}
              <Card className="flip-card-front absolute inset-0 w-full h-full">
                <CardContent className="flex flex-col items-center justify-center h-full p-8 text-center">
                  <Badge
                    className={cn(
                      "mb-4",
                      difficultyColors[currentCard.difficulty]
                    )}
                  >
                    {currentCard.difficulty}
                  </Badge>
                  <p className="text-xl font-medium">{currentCard.front}</p>
                  <p className="text-sm text-muted-foreground mt-4">
                    Click to flip
                  </p>
                </CardContent>
              </Card>

              {/* Back */}
              <Card className="flip-card-back absolute inset-0 w-full h-full bg-gradient-to-br from-primary/5 to-accent/5">
                <CardContent className="flex flex-col items-center justify-center h-full p-8 text-center">
                  <p className="text-lg whitespace-pre-line">
                    {currentCard.back}
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Rating Buttons */}
          <div className="flex items-center justify-center gap-4">
            <Button
              onClick={() => handleRating("hard")}
              variant="outline"
              className="flex-1 border-destructive/30 hover:bg-destructive/10 hover:text-destructive"
            >
              <ThumbsDown className="w-4 h-4 mr-2" />
              Hard
            </Button>
            <Button
              onClick={() => handleRating("good")}
              variant="outline"
              className="flex-1 border-warning/30 hover:bg-warning/10 hover:text-warning"
            >
              <Meh className="w-4 h-4 mr-2" />
              Good
            </Button>
            <Button
              onClick={() => handleRating("easy")}
              variant="outline"
              className="flex-1 border-success/30 hover:bg-success/10 hover:text-success"
            >
              <ThumbsUp className="w-4 h-4 mr-2" />
              Easy
            </Button>
          </div>

          {/* Navigation */}
          <div className="flex items-center justify-between">
            <Button
              onClick={() => {
                setCurrentIndex(Math.max(0, currentIndex - 1));
                setIsFlipped(false);
              }}
              variant="ghost"
              disabled={currentIndex === 0}
            >
              <ChevronLeft className="w-4 h-4 mr-2" />
              Previous
            </Button>
            <Button
              onClick={() => {
                setCurrentIndex(0);
                setIsFlipped(false);
              }}
              variant="ghost"
            >
              <RotateCcw className="w-4 h-4 mr-2" />
              Restart
            </Button>
            <Button
              onClick={() => {
                setCurrentIndex(Math.min(cards.length - 1, currentIndex + 1));
                setIsFlipped(false);
              }}
              variant="ghost"
              disabled={currentIndex === cards.length - 1}
            >
              Next
              <ChevronRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
